### PR TITLE
Fix fluentdconfig and syslogngconfig deletion

### LINKED ISSUE #1667: Fluentdconfig object deleted, pod is still running
> Bugs should be filed for issues encountered whilst operating logging-operator.
> You should first attempt to resolve your issues through the community support
> channels, e.g. Slack, in order to rule out individual configuration errors. [#logging-operator](https://slack.banzaicloud.io/)
> Please provide as much detail as possible.

**Describe the bug**:
Fluentdconfig object deleted but the pod is still running

**Expected behaviour**:
Fluentdconfig object deletion should stop the currently running pod.

**Steps to reproduce the bug**:
Dispatch a fluentdconfig (or use the e2e test case), delete the fluentdconfig object and the pod is still there.

**Additional context**:
`logging.Status.FluentdConfigName` can be used to decide whether a fluentdconfig:
- does not exist YET (.Status.FluentdConfigName is not set)
- NO LONGER exists (.Status.FluentdConfigName is set, but object is not there)

Questions: 
- [ ] If a fluentdconfig gets deleted should be owning loggingspec be reusable for a different one?

Maybe weak references could help here?

**Environment details**:
- Kubernetes version (e.g. v1.15.2):
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc):
- logging-operator version (e.g. 2.1.1):
- Install method (e.g. helm or static manifests):
- Logs from the misbehaving component (and any other relevant logs):
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:

/kind bug

### PR DESCRIPTION
**Pull request by OverOrion**
This PR aims to fix two problems:
- deleting a fluentdconfig/syslogngconfig resource should also delete the child resources (solved by changing the ownerreferences)
- deleting a logging resource should not be possible until a fluentdconfig/syslogngconfig resource exists. we don't delete the fluentdconfig/syslogngconfig forcefully because those are created by the user, but we can protect against this by using a finalizer. we send an event to the logging object for the user to be able to see other than looking at the operator logs

Fixes #1667.

Signed-off-by: Szilard Parrag <szilard.parrag@axoflow.com>

### CODE REVIEW

File: controllers/logging/logging_controller.go [hunk 1]
```diff
@@ -128,6 +130,18 @@ func (r *LoggingReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ct
 		return reconcile.Result{}, errors.WrapIfWithDetails(err, "failed to get logging resources", "logging", logging)
 	}
 
+	if ExternalFluentdRef := slices.Index(logging.Finalizers, logging.Status.FluentdConfigName); ExternalFluentdRef != -1 {
```
Comment (pepov) [inline controllers/logging/logging_controller.go:133]: I'm missing the deletiontimestamp check from here

File: controllers/logging/logging_controller.go [hunk 2]
```diff
@@ -128,6 +130,18 @@ func (r *LoggingReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ct
...
+		finalizer := logging.Finalizers[ExternalFluentdRef]
+		fluentdConfigName := types.NamespacedName{Namespace: logging.Spec.ControlNamespace, Name: finalizer}
+
+		fluentdConfigRefCleaned := r.cleanupFluentdConfigReference(ctx, log, &logging, fluentdConfigName)
+
+		if !fluentdConfigRefCleaned && logging.DeletionTimestamp != nil {
```
Comment (pepov) [inline controllers/logging/logging_controller.go:139]: why do we need the deletiontimestamp check here?

File: pkg/resources/model/reconciler.go [hunk 3]
```diff
@@ -235,6 +235,7 @@ func NewValidationReconciler(
 			}
 			logger.Info("found detached fluentd aggregator, making association", "name", resources.Fluentd.Configuration.Name)
 			resources.Logging.Status.FluentdConfigName = resources.Fluentd.Configuration.Name
+			resources.Logging.Finalizers = append(resources.Logging.Finalizers, resources.Fluentd.Configuration.Name)
```
Comment (pepov) [inline pkg/resources/model/reconciler.go:238]: I'm not sure this is the right place to do this. finalizer operations should be done at a single place

File: controllers/logging/logging_controller.go (hunk 1 above)
Comment (pepov) [inline controllers/logging/logging_controller.go:133]: also we should put up the finalizer somewhere here I beleive to keep it in one place

**Comment by OverOrion** [comment]
I have reworked the PR according to pepov's notes and using kubebuilder's docs: https://book.kubebuilder.io/reference/using-finalizers.

I also added a secondary fix which occured when logging switched from `fluentdConfig` to inline spec.

File: controllers/logging/logging_controller.go [hunk 4]
```diff
@@ -274,10 +285,53 @@ func (r *LoggingReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ct
...
+			controllerutil.AddFinalizer(logging, fluentdConfigFinalizer)
+			if err := r.Update(ctx, logging); err != nil {
+				return ctrl.Result{}, nil
+			}
+		}
+	} else {
+		// Marked for deletion, check for fluentdConfig
+		fluentdConfigName := types.NamespacedName{Namespace: logging.Spec.ControlNamespace, Name: logging.Status.FluentdConfigName}
+		if controllerutil.ContainsFinalizer(logging, fluentdConfigFinalizer) && r.isExistingFluentdConfig(ctx, fluentdConfigName) {
+			return reconcile.Result{}, errors.NewWithDetails("failed to delete logging resources, delete fluentdConfig first", "fluentdConfig", logging.Status.FluentdConfigName)
```
Comment (pepov) [inline controllers/logging/logging_controller.go:309]: I'm thinking about this hard because the user won't have any feedback about this. How about one of the following?
- we could actually remove the fluentdconfig resource here
- we could update the logging status so that the user see what's happening

or maybe it would be enough to use a logging ownerref on the fluentdconfig?

File: controllers/logging/logging_controller.go [hunk 5]
```diff
@@ -274,10 +285,53 @@ func (r *LoggingReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ct
...
+		}
+		controllerutil.RemoveFinalizer(logging, fluentdConfigFinalizer)
+		if err := r.Update(ctx, logging); err != nil {
```
Comment (pepov) [inline controllers/logging/logging_controller.go:312]: what happens to the error here?

**Review by kristofgyuracz — APPROVED** [review]

File: controllers/logging/logging_controller.go (hunk 4 above)
Comment (OverOrion) [reply controllers/logging/logging_controller.go:322]: We can not update the status once an object is marked for deletion: https://kubernetes.io/docs/concepts/overview/working-with-objects/finalizers/#how-finalizers-work (see the note section)

Removing the fluentdconfig might be unexpected (admin deletes logging, tenant loses it's fluentdconfig object)

File: controllers/logging/logging_controller.go [hunk 6]
```diff
@@ -332,6 +376,14 @@ func (r *LoggingReconciler) isExistingFluentdConfig(ctx context.Context, fluentd
 	return true
 }
 
+func (r *LoggingReconciler) isExistingSyslogNGConfig(ctx context.Context, syslogNGConfigref types.NamespacedName) bool {
+	var fluentdConfig loggingv1beta1.SyslogNGConfig
+	if err := r.Client.Get(ctx, syslogNGConfigref, &fluentdConfig); err != nil && apierrors.IsNotFound(err) {
```
Comment (orymate) [inline controllers/logging/logging_controller.go:381]:
```suggestion
	var config loggingv1beta1.SyslogNGConfig
	if err := r.Client.Get(ctx, syslogNGConfigref, &config); err != nil && apierrors.IsNotFound(err) {
```

**Review by orymate — APPROVED** [review]

**Review by tarokkk — APPROVED** [review]

File: controllers/logging/logging_controller.go [hunk 7]
```diff
@@ -302,15 +309,21 @@ func (r *LoggingReconciler) checkFluentdConfigFinalizer(ctx context.Context, log
...
 		if err := r.Update(ctx, logging); err != nil {
-			return ctrl.Result{}, nil
+			return r.cleanupFluentdConfigReference(ctx, logging, log)
 		}
 	}
 	return ctrl.Result{}, nil
 }
 
+func (r *LoggingReconciler) cleanupFluentdConfigReference(ctx context.Context, logging *loggingv1beta1.Logging, log logr.Logger) (ctrl.Result, error) {
+	log.Info("cleaned up fluentdConfigRef", "name", logging.Status.FluentdConfigName)
```
[the remark this answers is not in the document]
Comment (pepov) [reply controllers/logging/logging_controller.go]: reworded

**Review by pepov — APPROVED** [review]
