### PR TITLE
fix(configcheck): wait for secrets to be available

### LINKED ISSUE #1406: fluentd configcheck terminated before running
**Describe the bug**:

In one of the bigger cluster we observe a regression that the configcheck pod goes in Terminating state before the pod is started after a config change in Flows/Outputs. 

**Expected behaviour**:

configcheck pod started after config change, running to completed if no errors occured.

**Steps to reproduce the bug**:

Cluster with 40 nodes and 80 flows/outputs

**Additional context**:

**Environment details**:
- Kubernetes version (e.g. v1.15.2): 1.23.16
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): Rancher RKE
- logging-operator version (e.g. 2.1.1): 4.3.0-rc0
- Install method (e.g. helm or static manifests): Helm
- Logs from the misbehaving component (and any other relevant logs):
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:

event log:
```
0s          Normal    Scheduled                pod/logging-bronze-fluentd-configcheck-6e8fd6c1           Successfully assigned caas-logging-system/logging-bronze-fluentd-configcheck-6e8fd6c1 to worker20-az2
0s          Warning   FailedMount              pod/logging-bronze-fluentd-configcheck-6e8fd6c1           MountVolume.SetUp failed for volume "app-config" : secret "logging-bronze-fluentd-configcheck-app-6e8fd6c1" not found
0s          Warning   FailedMount              pod/logging-bronze-fluentd-configcheck-6e8fd6c1           MountVolume.SetUp failed for volume "output-secret" : secret "logging-bronze-fluentd-configcheck-output-6e8fd6c1" not found
0s          Normal    Pulling                  pod/logging-bronze-fluentd-configcheck-6e8fd6c1           Pulling image "mtr.devops.telekom.de/kubelogging/fluentd:v1.15"
0s          Normal    Pulled                   pod/logging-bronze-fluentd-configcheck-6e8fd6c1           Successfully pulled image "mtr.devops.telekom.de/kubelogging/fluentd:v1.15" in 354.910688ms (354.918716ms including waiting)
0s          Normal    Created                  pod/logging-bronze-fluentd-configcheck-6e8fd6c1           Created container fluentd
0s          Normal    Started                  pod/logging-bronze-fluentd-configcheck-6e8fd6c1           Started container fluentd
0s          Normal    Killing                  pod/logging-bronze-fluentd-configcheck-6e8fd6c1           Stopping container fluentd
0s          Normal    Scheduled                pod/logging-bronze-fluentd-configcheck-6e8fd6c1           Successfully assigned caas-logging-system/logging-bronze-fluentd-configcheck-6e8fd6c1 to worker20-az2
0s          Normal    Pulling                  pod/logging-bronze-fluentd-configcheck-6e8fd6c1           Pulling image "mtr.devops.telekom.de/kubelogging/fluentd:v1.15"
0s          Normal    Pulled                   pod/logging-bronze-fluentd-configcheck-6e8fd6c1           Successfully pulled image "mtr.devops.telekom.de/kubelogging/fluentd:v1.15" in 321.345112ms (321.354422ms including waiting)
0s          Normal    Created                  pod/logging-bronze-fluentd-configcheck-6e8fd6c1           Created container fluentd
0s          Normal    Started                  pod/logging-bronze-fluentd-configcheck-6e8fd6c1           Started container fluentd
```

The missing secrets are there some milliseconds later, a second try the config-check Pod is in state completed. Maybe he can wait until the secrets are there?

/kind bug

### PR DESCRIPTION
**Pull request by OverOrion**
This PR aims to delay the configcheck pod creation until secrets are available.

Fixes #1406.

### CODE REVIEW

File: pkg/resources/syslogng/configcheck.go [hunk 1]
```diff
@@ -48,6 +48,16 @@ func (r *Reconciler) configHash() (string, error) {
 	return fmt.Sprintf("%x", hasher.Sum32()), nil
 }
 
+func (r *Reconciler) CheckForObjectExistence(ctx context.Context, object client.Object) (*ConfigCheckResult, error) {
```
Comment (OverOrion) [inline pkg/resources/syslogng/configcheck.go:51]: The caller (`func Reconcile`) seems to be responsible for returning a `RequeueAfter <time>`, so I opted for just returning a `not-Ready` result, which will make it try again in a minute. Is it acceptable, or should we change the time?

File: pkg/resources/fluentd/appconfigmap.go [hunk 2]
```diff
@@ -77,6 +77,16 @@ func (r *Reconciler) hasConfigCheckPod(ctx context.Context, hashKey string) (boo
 	return true, nil
 }
 
+func (r *Reconciler) CheckForObjectExistence(ctx context.Context, object client.Object) (*ConfigCheckResult, error) {
+	if err := r.Client.Get(ctx, client.ObjectKeyFromObject(object), object); err != nil {
```
Comment (pepov) [inline pkg/resources/fluentd/appconfigmap.go:81]: In case the error is `apierrors.IsNotFound(err)` we could also return without an error, since we will retry the reconcile once the secret update is received automatically. What do you think?

File: pkg/resources/syslogng/configcheck.go (hunk 1 above)
Comment (aslafy-z) [reply pkg/resources/syslogng/configcheck.go:51]: 1 minute looks a bit long to me, is there any way to reduce this delay for this use case?

Comment (pepov) [reply pkg/resources/syslogng/configcheck.go:51]: That is just a fail-safe setting, it shouldn't take a minute. The controller watches the secret it creates, so as soon as the secret is created a reconcile will be triggered. We could even return with a reconcile result:true there, but the 1 minute shouldn't hurt either.

Comment (pepov) [reply pkg/resources/syslogng/configcheck.go:51]: @OverOrion however the notready result won't take effect currently as you return an error as well. The end result is going to be the same, so I'm not insisting on changing this, but in case the object has simply not yet been received through the watch, then it looks cleaner to me to return without an error.

Comment (OverOrion) [reply pkg/resources/syslogng/configcheck.go:51]: You are right, changed it accordingly, thanks for it!

File: pkg/resources/fluentd/appconfigmap.go (hunk 2 above)
Comment (OverOrion) [reply pkg/resources/fluentd/appconfigmap.go:81]: I agree, thanks for it!

**Review by kristofgyuracz — APPROVED** [review]
LGTM, thanks.

File: pkg/resources/fluentd/appconfigmap.go [hunk 3]
```diff
@@ -77,6 +77,21 @@ func (r *Reconciler) hasConfigCheckPod(ctx context.Context, hashKey string) (boo
...
+		if apierrors.IsNotFound(err) {
+			objNotFoundMsg := fmt.Sprintf("Object: %s (kind: secret) in namespace %s not found", object.GetName(), object.GetNamespace())
```
Comment (aslafy-z) [inline pkg/resources/fluentd/appconfigmap.go:83]:
```suggestion
			objNotFoundMsg := fmt.Sprintf("Object %s (kind: secret) in namespace %s not found", object.GetName(), object.GetNamespace())
```

Comment (aslafy-z) [reply pkg/resources/fluentd/appconfigmap.go:83]: Can't object kind be extracted from client.Object?
