### PR TITLE
Make mutating webhook idempotent

### LINKED ISSUE #1444: Tailer-Webhook Producing an Invalid Spec
> Bugs should be filed for issues encountered whilst operating logging-operator.
> You should first attempt to resolve your issues through the community support
> channels, e.g. Slack, in order to rule out individual configuration errors. [#logging-operator](https://slack.banzaicloud.io/)
> Please provide as much detail as possible.

**Describe the bug**:
After setting up the Tailer-Webhook according to the [Docs](https://kube-logging.dev/docs/configuration/extensions/tailer-webhook/#multi-container-pods), it does not seem generate a valid spec and instead produces one with duplicate volume name, mountPath, and container name. It is as though either 2 mutations occurred or the operator tried to mutate twice. I have confirmed that there is only a single operator pod, service, and  mutating webhook.

Test:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  annotations:
    "sidecar.logging-extensions.banzaicloud.io/tail": "/var/log/date"
spec:
  containers:
    - image: debian
      name: sample-container
      command: ["/bin/sh", "-c"]
      args:
        - while true; do
          date >> /yolo/date;
          sleep 1;
          done
```

Result:
```bash
The Pod "test-pod" is invalid:
* spec.volumes[2].name: Duplicate value: "sample-container-var-log"
* spec.containers[0].volumeMounts[2].mountPath: Invalid value: "/var/log": must be unique
* spec.containers[2].name: Duplicate value: "sample-container-var-log-date"
```

**Expected behaviour**:
A concise description of what you expected to happen.

**Steps to reproduce the bug**:
1. Setup Prerequisites per above Docs(Cert)
2. Setup Webhook(ENV var, MutatingWebhookConfig, Service)
3. Attempt to create the example pod.

**Additional context**:
We tested this across 4 identical  clusters, all with the same results.

**Environment details**:
- Kubernetes version (e.g. v1.15.2): 1.27.4
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): EKS
- logging-operator version (e.g. 2.1.1): 4.2.3
- Install method (e.g. helm or static manifests): [Operator Helm Chart](https://github.com/kube-logging/helm-charts/tree/main/charts/logging-operator) and [Logging Helm Chart](https://github.com/kube-logging/helm-charts/tree/main/charts/logging-operator-logging)
- Logs from the misbehaving component (and any other relevant logs):
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:

/kind bug

### PR DESCRIPTION
**Pull request by OverOrion**
Needs https://github.com/kube-logging/logging-operator/pull/1494 before merging.

Fixes #1444.

### CODE REVIEW

File: pkg/webhook/podhandler/podhandler.go [hunk 1]
```diff
@@ -125,5 +126,40 @@ func (p *PodHandler) Handle(ctx context.Context, req admission.Request) admissio
 		return admission.Errored(http.StatusInternalServerError, err)
 	}
 
-	return admission.PatchResponseFromRaw(req.Object.Raw, marshaledPod)
+	rv := admission.PatchResponseFromRaw(req.Object.Raw, marshaledPod)
+	return rv
```
Comment (pepov) [inline pkg/webhook/podhandler/podhandler.go:130]:
```suggestion
	return admission.PatchResponseFromRaw(req.Object.Raw, marshaledPod)
```

File: pkg/webhook/podhandler/podhandler.go [hunk 2]
```diff
@@ -108,15 +109,15 @@ func (p *PodHandler) Handle(ctx context.Context, req admission.Request) admissio
...
 
 		sideCars, volumes, volumeMounts := p.sideCarsForContainer(container.Name, filePaths)
 
 		// Append the new data to the podspec
-		pod.Spec.Containers = append(pod.Spec.Containers, sideCars...)
-		pod.Spec.Volumes = append(pod.Spec.Volumes, volumes...)
-		pod.Spec.Containers[idx].VolumeMounts = append(pod.Spec.Containers[idx].VolumeMounts, volumeMounts...)
+		if err := p.podHandlerHelper(pod, sideCars, volumes, volumeMounts); err != nil {
+			return *err
+		}
```
Comment (pepov) [inline pkg/webhook/podhandler/podhandler.go:120]:
```suggestion
		if resp := p.podHandlerHelper(pod, sideCars, volumes, volumeMounts); resp != nil {
			return *resp
		}
```

File: pkg/webhook/podhandler/podhandler.go [hunk 3]
```diff
@@ -125,5 +126,40 @@ func (p *PodHandler) Handle(ctx context.Context, req admission.Request) admissio
...
+
+func (p *PodHandler) podHandlerHelper(podToModify *corev1.Pod, sideCars []corev1.Container, volumes []corev1.Volume, volumeMounts []corev1.VolumeMount) *admission.Response {
+	duplicateValuesMsg := "webhook mutation would result in duplicate values, returning"
+	for idx, sideCar := range sideCars {
+		sideCar := sideCar
+		if seqs.Any(seqs.FromSlice(podToModify.Spec.Containers), func(c corev1.Container) bool {
+			return c.Name == sideCar.Name
+		}) {
+			p.Log.Info(duplicateValuesMsg)
+			rv := admission.Allowed(duplicateValuesMsg)
```
Comment (pepov) [inline pkg/webhook/podhandler/podhandler.go:141]: Why not admission.Denied? I beleive this should result in an error on the user side

File: pkg/webhook/podhandler/podhandler.go [hunk 4]
```diff
@@ -125,5 +126,40 @@ func (p *PodHandler) Handle(ctx context.Context, req admission.Request) admissio
...
+		}
+	}
+
+	for _, volume := range volumes {
+		volume := volume
+		if seqs.Any(seqs.FromSlice(podToModify.Spec.Volumes), func(v corev1.Volume) bool {
+			return v.Name == volume.Name
+		}) {
+			p.Log.Info(duplicateValuesMsg)
+			rv := admission.Allowed(duplicateValuesMsg)
```
Comment (pepov) [inline pkg/webhook/podhandler/podhandler.go:157]: same here: I would consider denying the request here

File: pkg/webhook/podhandler/podhandler.go (hunk 3 above)
Comment (OverOrion) [reply pkg/webhook/podhandler/podhandler.go:141]: My reasoning was that it would not be idempotent if we denied the request, but after giving it a bit more thought it seems to be idempotent on the server side (appends only if needed) but the user indeed should receive an error.

**Comment by aslafy-z** [comment]
Will this be ported to main?
