### PR TITLE
fix(webhook-handler): followup regarding decoding changes in controller-runtime

### LINKED ISSUE #1493: bug: controller-runtime followup is needed regarding `InjectDecoder`
> Bugs should be filed for issues encountered whilst operating logging-operator.
> You should first attempt to resolve your issues through the community support
> channels, e.g. Slack, in order to rule out individual configuration errors. [#logging-operator](https://slack.banzaicloud.io/)
> Please provide as much detail as possible.

During the investigation of https://github.com/kube-logging/logging-operator/issues/1444 we found that with 4.3 the controller-runtime dependency has been updated, however followups were not done.
See: https://github.com/kubernetes-sigs/controller-runtime/issues/2504

**Describe the bug**:
Followup is required to support newer controller-runtime versions.

**Expected behaviour**:
The webhook tailer working fine.

**Steps to reproduce the bug**:
See the original issue for reproduction steps, but in a nutshell: configure a `webhooktailer`, start a pod and see a crash:
```
2023/09/27 13:49:11 http: panic serving 10.244.0.1:26229: runtime error: invalid memory address or nil pointer dereference                                                                                                                                   
goroutine 2399 [running]:                                                                                                                                                                                                                                    
net/http.(*conn).serve.func1()                                                                                                                                                                                                                               
    /usr/local/go/src/net/http/server.go:1854 +0xbf                                                                                                                                                                                                          
panic({0x18a13c0, 0x2a05910})                                                                                                                                                                                                                                
    /usr/local/go/src/runtime/panic.go:890 +0x263                                                                                                                                                                                                            
sigs.k8s.io/controller-runtime/pkg/webhook/admission.(*Decoder).DecodeRaw(0x0, {{0xc0003b8d80, 0xcdb, 0xd80}, {0x0, 0x0}}, {0x1d54980, 0xc000d36d80})                                                                                                        
    /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/webhook/admission/decode.go:76 +0x13a                                                                                                                                                             
sigs.k8s.io/controller-runtime/pkg/webhook/admission.(*Decoder).Decode(_, {{{0xc001069f20, 0x24}, {{0x0, 0x0}, {0xc000716d08, 0x2}, {0xc000716d0a, 0x3}}, {{0x0, ...}, ...}, ...}}, ...)                                                                     
    /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/webhook/admission/decode.go:49 +0x8e                                                                                                                                                              
github.com/kube-logging/logging-operator/pkg/webhook/podhandler.(*PodHandler).Handle(_, {_, _}, {{{0xc001069f20, 0x24}, {{0x0, 0x0}, {0xc000716d08, 0x2}, {0xc000716d0a, ...}}, ...}})                                                                       
    /usr/local/src/logging-operator/pkg/webhook/podhandler/podhandler.go:88 +0xac                       
```


**Environment details**:
- Kubernetes version (e.g. v1.15.2): 1.27.3
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): -
- logging-operator version (e.g. 2.1.1): 4.3
- Install method (e.g. helm or static manifests): helm
- Logs from the misbehaving component (and any other relevant logs):
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:

/kind bug

### PR DESCRIPTION
**Pull request by OverOrion**
Also added some logs / error reporting where it seemed sensible.

Fixes #1493.

### CODE REVIEW

File: pkg/webhook/podhandler/podhandler.go [hunk 1]
```diff
@@ -116,14 +122,9 @@ func (p *PodHandler) Handle(ctx context.Context, req admission.Request) admissio
 
 	marshaledPod, err := json.Marshal(pod)
 	if err != nil {
+		log.Error(errors.New("pod marshaling failed"), err.Error())
```
Comment (pepov) [inline pkg/webhook/podhandler/podhandler.go:125]: this should also be reversed:
```suggestion
		log.Error(err, "pod marshaling failed")
```

**Review by pepov — APPROVED** [review]

**Review by pepov — CHANGES_REQUESTED** [review]
please rebase this against release-4.4

**Review by pepov — APPROVED** [review]

**Comment by aslafy-z** [comment]
Don't you prefer to merge this into master & cherry-pick it to release-4.4 instead of merging it into release-4.4?
